Copies of books
MaxTheComputerer/Bookish pull request #5
Opened 2022-07-13 10:42 UTC by MaxTheComputerer

- Books can be checked in and out
- Overdue books are highlighted and the numbers of days late is shown
- Still to do: Populate "Borrower" dropdown with list of library members (need changes from #4)

Will conflict with #4 because this still uses just the Home controller.

2022-07-13 12:34 UTC, cec200wire approved these changes

2022-07-13 16:51 UTC, emilypatsko requested changes
Few small changes, but looks good so far!

2022-07-13 16:51 UTC, emilypatsko commented on Bookish/Controllers/HomeController.cs
> +        var result = BookCopyService.GetCopies(book);
I like that this logic lives in a service! However the service itself should probably not live in the Models folder, but in a separate Services folder. I left some similar comments on Claire's PR about some of the classes which contained useful methods. I suggested renaming the classes to something like `EditBooksHelper` and putting them in a Helpers folder, but you two should probably chat and come up with a common solution.

2022-07-13 16:51 UTC, emilypatsko commented on Bookish/Models/BookCopyModel.cs
> +public class CheckOutCopyModel
I reckon this could go in a separate file

2022-07-13 16:51 UTC, emilypatsko commented on Bookish/Views/Shared/_BookTable.cshtml
> +                    @using (Html.BeginForm("ViewCopies", "Home", FormMethod.Get))
If you just want a button to direct to a specific controller action, you don't need a whole form - you can supply a button input with a `Url.Action`. Take a look at the top answer [here](https://stackoverflow.com/questions/2503923/html-button-calling-an-mvc-controller-and-action-method)

2022-07-13 16:51 UTC, emilypatsko commented on Bookish/Views/Shared/_CopyTable.cshtml
> +            <tr class="@(!copy.IsAvailable() && copy.OverdueTime().Days >= 1 ? "table-danger" : "")">
Nice touch!

2022-07-14 10:06 UTC, MaxTheComputerer commented
> Few small changes, but looks good so far!

Changes have been made!

2022-07-14 10:25 UTC, MaxTheComputerer commented
Resolved merge conflicts

2022-07-14 11:10 UTC, emilypatsko approved these changes
I've left a couple comments - you don't _have_ to make these changes, but they might be nice to look into. Otherwise I've approved 😄

2022-07-14 11:10 UTC, emilypatsko commented on Bookish/Views/Shared/_CopyTable.cshtml
> +                    }
You could probably reduce this to one line using a ternary and string interpolation, something like:
```
<td>@(copy.OverdueTime().Days >= 1 ? $"{copy.OverdueTime().Days} days" : "")</td>
```

2022-07-14 11:10 UTC, emilypatsko commented on Bookish/Views/Shared/_CopyTable.cshtml
> +<!-- Modal -->
Nice use of commenting to make it clear what this is - I wonder if this modal block could be separated out into a partial view?

2022-07-14 11:29 UTC, merged